### ISSUE TITLE
The "-d" does not what it supposed to...

### ISSUE THREAD

**Issue by Code-Nycticebus** [Code-Nycticebus/pybuildc#30]
to relative paths:

```toml
[dependencies]
mylib = {include=["../deps/mylib/include"], ...}
```

does not work with the command:

```bash
pybuildc -d path/to/project build
```
