### ISSUE TITLE
Prebuild script

### ISSUE THREAD

**Issue by Code-Nycticebus** [Code-Nycticebus/pybuildc#41]
add scripts that you want to run before actual build step.

```toml
build_scripts = ["generate.sh"]
```

and maybe even add that to dependencies

```toml
[dependencies]
glew = { dir="...", lib="...", build_script=["build_debian.sh"]}
```
