### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by Code-Nycticebus** [Code-Nycticebus/pybuildc#6]
there should be a way to handle dependecies.

in the pybuildc.toml
```toml
[dependecies]
math = {type="so", lib="-lm"}
custom = {type="so", include=["-I/usr/lib/custom"], lib=["-L/usr/lib/custom/lib", "-lcustom"]}
other = {type="pybuildc", project="https://github.com/Code-Nycticebus/pybuildc.git"}
```

like this?
