### ISSUE TITLE
Basic dependencies

### ISSUE THREAD

**Issue by Code-Nycticebus** [Code-Nycticebus/pybuildc#8]
get basic dependencies working!

```toml
[dependencies]
math = {libs=["-lm"]}
```
